#!/sbin/openrc-run

# fallback values for /etc/conf.d/whisparr
: ${command_user:=whisparr:whisparr}
: ${directory:=/var/lib/whisparr}
: ${logdir:=/var/log/whisparr}
: ${umask:=0002}

name=whisparr
description="Whisparr daemon"
command="/usr/lib/whisparr/bin/Whisparr"
command_args="-nobrowser -data=$directory"
command_background=true

pidfile="/run/$name.pid"
output_log="$logdir/output.log"
error_log="$logdir/error.log"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory" "$logdir"
	checkpath -f -o "$command_user" "$output_log" "$error_log"
}
