#!/sbin/openrc-run

# fallback values for /etc/conf.d/sonarr
: ${command_user:=sonarr:sonarr}
: ${directory:=/var/lib/sonarr}
: ${umask:=0002}

name=sonarr
description="Sonarr daemon"
command="/usr/lib/sonarr/bin/Sonarr"
command_args="-nobrowser -data=$directory"
command_background=true
pidfile="/run/$name.pid"

depend() {
	need net
	use dns logger netmount
}

start_pre() {
	checkpath -d -o "$command_user" "$directory"
}
